import = [
    "~/.config/alacritty/themes/catppuccin_frappe.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 2
padding.y = 2
# decorations = "Buttonless"
# opacity = 0.4
# blur = true
option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 14
