require "user.core.colorscheme"
require "user.core.options"
require "user.core.keymaps"
require "user.plugins"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.comment"
require "user.gitsigns"
require "user.lualine"

