require "user.plugins-setup"
require "user.core.colorscheme"
require "user.core.options"
require "user.core.keymaps"
require "user.plugins.nvim-cmp"
require "user.plugins.lsp"
require "user.plugins.telescope"
require "user.plugins.treesitter"
require "user.plugins.comment"
require "user.plugins.gitsigns"
require "user.plugins.lualine"

